export const UPDATE_LOGIN_VALUE = 'UPDATE_LOGIN_VALUE';
export const UPDATE_NAME_VALUE = 'UPDATE_NAME_VALUE';
export const UPDATE_PASS_VALUE = 'UPDATE_PASS_VALUE';
export const UPDATE_CONFIRM_PASS_VALUE = 'UPDATE_CONFIRM_PASS_VALUE';
export const RESET_REGISTRATION_FORM = 'RESET_REGISTRATION_FORM';
